apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: ns-react-app-master
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: localhost:32000/prime-number-frontend:master-c26b184169e4aa429b96da4824d0e20309800011
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
