apiVersion: v1
kind: Service
metadata:
  name: prime-number-webapi-service
  namespace: ns-react-app-develop
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31595  # Mantén el NodePort para accesibilidad externa
  selector:
    app: prime-number-webapi
