apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-number-webapi
  namespace: ns-react-app-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-number-webapi
  template:
    metadata:
      labels:
        app: prime-number-webapi
    spec:
      containers:
      - name: prime-number-webapi
<<<<<<< HEAD
        image: localhost:32000/prime-number-backend:master
=======
        image: localhost:32000/prime-number-backend:master-20ed9dbeaea57c7b781fcd507a52bcd90fbfd51a
>>>>>>> 340a422c0045a257a5eb08ef93bea21f1a276032
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__PrimeNumberDB
          value: "Server=mssql-service;Database=PrimeNumberDB;User ID=sa;Password=SQLtest1;"
